# Generated by Django 6.1.1 on 2026-09-08 06:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in standard currency', max_digits=8)),
            ],
            options={
                'ordering': ['vehicle_type'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('booking_date', models.DateField()),
                ('expected_arrival_time', models.TimeField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Total billable hours rounded up via ceiling logic', null=True)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='parking.booking')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(help_text='e.g., A-01, B-02', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkingarea')),
            ],
            options={
                'ordering': ['parking_area', 'slot_number'],
                'unique_together': {('parking_area', 'slot_number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingslot'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Parking Staff'), ('CUSTOMER', 'Customer / Driver')], default='CUSTOMER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='e.g., BA-02-PA-1234 or DL-01-AB-1234', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.vehicle'),
        ),
    ]
